;; Problem 2

;; Each new term in the Fibonacci sequence is generated by adding the previous
;; two terms. By starting with 1 and 2, the first 10 terms will be:

;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; By considering the terms in the Fibonacci sequence whose values do not
;; exceed four million, find the sum of the even-valued terms.

(ns project-euler-clojure.problem-002)

(defn fibonacci-sequence
  ([] (fibonacci-sequence 1 2))
  ([a b] (lazy-seq (cons a (fibonacci-sequence b (+ a b))))))

(defn solution-002
  []
  (->>
   (fibonacci-sequence)
   (take-while #(< % 4000000))
   (filter even?)
   (reduce +)))

(solution-002)
